// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAq9oHVqENSyOKbRqwDVaeKwN0fwyQL8tM',
    appId: '1:579213889163:web:8347a4929f14720bb50e8e',
    messagingSenderId: '579213889163',
    projectId: 'yasir-fashion-stores',
    authDomain: 'yasir-fashion-stores.firebaseapp.com',
    storageBucket: 'yasir-fashion-stores.firebasestorage.app',
    measurementId: 'G-K5VTEYR1E9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBI-P1Tafei_JCBoJlJqLRRA0_iwMsxK5E',
    appId: '1:579213889163:android:81ab923ace13f48ab50e8e',
    messagingSenderId: '579213889163',
    projectId: 'yasir-fashion-stores',
    storageBucket: 'yasir-fashion-stores.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQDrxq-hyJie9bVcsUFbw-4jNUoKahixs',
    appId: '1:579213889163:ios:b2c9d67e46bea5a8b50e8e',
    messagingSenderId: '579213889163',
    projectId: 'yasir-fashion-stores',
    storageBucket: 'yasir-fashion-stores.firebasestorage.app',
    iosClientId: '579213889163-sckugg8eiqah0b0232k6on3d1mevqj1r.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQDrxq-hyJie9bVcsUFbw-4jNUoKahixs',
    appId: '1:579213889163:ios:b2c9d67e46bea5a8b50e8e',
    messagingSenderId: '579213889163',
    projectId: 'yasir-fashion-stores',
    storageBucket: 'yasir-fashion-stores.firebasestorage.app',
    iosClientId: '579213889163-sckugg8eiqah0b0232k6on3d1mevqj1r.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAq9oHVqENSyOKbRqwDVaeKwN0fwyQL8tM',
    appId: '1:579213889163:web:04b539cbe591006bb50e8e',
    messagingSenderId: '579213889163',
    projectId: 'yasir-fashion-stores',
    authDomain: 'yasir-fashion-stores.firebaseapp.com',
    storageBucket: 'yasir-fashion-stores.firebasestorage.app',
    measurementId: 'G-SV3ZC60MCH',
  );

}